### ISSUE TITLE
NItem#setString not saving value at 1.20.3/1.20.4 (1_20_R3)

### ISSUE THREAD

**Issue by ianlibanio** [LoneDev6/FastNBT#3]
When using setString, and then trying to get it value isn't getting returned, and null returns instead. (Paper 1.20.4 latest release)

Example code:
```java
NItem.of(itemStack).setString("id", "example"); // Sets "id" to example into itemStack
String value = NItem.of(itemStack).getString("id"); // returns null
```

I did a small investigation and found out value returned from NMS ItemStack#getOrCreateTag() isn't containing the tag set, and also tested only getting the tag to ensure a new one isn't getting created and can confirm tag existed.

**Comment by LoneDev6** [comment]
Because you are using the API in a wrong way.

```java
NItem nItem = NItem.of(itemStack);
nItem.setString("id", "example"); // Sets "id" to example into itemStack

String value = nItem.getString("id"); // returns null
// Do your stuff here

// Save if necessary
nItem.save();
```

**Comment by ianlibanio** [comment]
Yeah, looks like I missed the save part. Appreciate you for making this NBT API public.

Only a suggestion, might be good to put this #save() part at README examples.

**Comment by LoneDev6** [comment]
Done! ty
